openapi: 3.0.3
info:
  title: Segments API
  description: Segments API
  version: 1.0.0

servers:
  - url: 'http://localhost:8080/api/v1'
    description: Local server


components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          example: 'Something went wrong'
    ValidationError:
      type: object
      properties:
        error:
          type: string
          example: 'Validation error'
        fields:
          type: array
          items:
            type: string
            example: 'slug is too short, min length is 3'
    CreateSegment:
      type: object
      properties:
        slug:
          type: string
          example: 'AVITO_VOICE_MESSAGES'
    Segment:
      type: object
      properties:
        id:
          type: string
          example: '5f8b0b9b-1b9a-4e1a-8c0e-3b2b1b1b1b1b'
        slug:
          type: string
          example: 'AVITO_VOICE_MESSAGES'
    UpdateUserSegments:
      type: object
      properties:
        join:
          type: array
          description: List of segments names, which user should be added to
          items:
            type: string
            example: 'AVITO_VOICE_MESSAGES'
        leave:
          type: array
          description: List of segments names, which user should be removed from
          items:
            type: string
            example: 'AVITO_VOICE_MESSAGES'
    UserSegment:
      type: object
      properties:
        slug:
          type: string
          example: 'AVITO_VOICE_MESSAGES'


paths:
  /segment:
    post:
      tags:
        - segment
      summary: Create a new segment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSegment'
      responses:
        '201':
          description: Segment created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Segment'
        '400':
          description: Invalid input, object invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: An existing item already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Unprocessable entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /segment/{id}:
    delete:
      tags:
        - segment
      summary: Delete segment by id
      parameters:
        - name: id
          in: path
          required: true
          description: Segment id
          schema:
            type: string
            example: '5f8b0b9b-1b9a-4e1a-8c0e-3b2b1b1b1b1b'
      responses:
        '204':
          description: Segment deleted
        '404':
          description: Segment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /user/{id}/segment:
    put:
      tags:
        - segment
      summary: Add/remove user to segments
      parameters:
        - name: id
          in: path
          required: true
          description: User id
          schema:
            type: number
            example: 322
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserSegments'
      responses:
        '204':
          description: User segments updated
        '400':
          description: Invalid input, object invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Unprocessable entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      tags:
        - segment
      summary: Get user segments
      parameters:
        - name: id
          in: path
          required: true
          description: User id
          schema:
            type: number
            example: 322
        - name: status
          in: query
          required: false
          description: Segment status
          schema:
            type: string
            example: 'active'
            default: 'active'
            enum: [ 'active' ]
      responses:
        '200':
          description: User segments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserSegment'
        '400':
          description: Invalid input, object invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'



